"use client";
import {useCallback,useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Leaf,Moon,BookOpen,Sprout,Droplets,LayoutDashboard,Settings as SettingsIcon,Plus,ArrowUpRight,Check,Download,Upload,LogOut,Lock,Trash2,Pencil,ChevronRight,RefreshCw,FileSpreadsheet,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Toaster,toast} from 'sonner';
import {defaultSettings,today,labels,sleepHours,onTime,presets,due,frequencyText,countDue,daysInMonth,recordTitle,recordDetail,type LifeRecord,type Habit,type Settings,type Kind} from '@/lib/life';
import {api,authenticate,clearAuthToken,logout} from '@/lib/api-client';
type Profile={id:string;name:string;email:string;settings:Settings;revision:number};
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[]|[string,string][];label?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label||'选择'}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const [v,t]=typeof o==='string'?[o,o]:o;return <SelectItem key={v} value={v}>{t}</SelectItem>})}</SelectContent></Select>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={'field '+(wide?'wide':'')}><span>{label}</span>{children}</label>}
const icons={sleep:Moon,study:BookOpen,meal:Droplets,check:Sprout};
const navs=[{id:'home',name:'生活总览',Icon:LayoutDashboard},{id:'records',name:'日常记录',Icon:BookOpen},{id:'habits',name:'习惯打卡',Icon:Sprout},{id:'settings',name:'个人设置',Icon:SettingsIcon}];
export default function Home(){
const [page,setPage]=useState('home'),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[setup,setSetup]=useState(false),[canSetup,setCanSetup]=useState(false),[setupCodeRequired,setSetupCodeRequired]=useState(false),[records,setRecords]=useState<LifeRecord[]>([]),[habits,setHabits]=useState<Habit[]>([]);
const [month,setMonth]=useState(today().slice(0,7)),[day,setDay]=useState(''),[tab,setTab]=useState('sleep'),[habitTab,setHabitTab]=useState('运动'),[auth,setAuth]=useState(false),[edit,setEdit]=useState<LifeRecord|null>(null),[habitEdit,setHabitEdit]=useState<Habit|null>(null),[detail,setDetail]=useState<LifeRecord|null>(null),[remove,setRemove]=useState<LifeRecord|null>(null),[busy,setBusy]=useState(false),[imported,setImported]=useState<{records:LifeRecord[];warnings:string[]}|null>(null);
const settings=profile?.settings||defaultSettings;
const reload=useCallback(async()=>{try{const s=await api<{user:Profile|null;setup:boolean;canSetup:boolean;setupCodeRequired:boolean}>('session');setProfile(s.user);setSetup(s.setup);setCanSetup(s.canSetup);setSetupCodeRequired(s.setupCodeRequired);if(s.user){const [rs,hs]=await Promise.all([api<LifeRecord[]>('records'),api<Habit[]>('habits')]);setRecords(rs);setHabits(hs)}else{clearAuthToken();setRecords([]);setHabits([])}setLoadError('')}catch(e){setLoadError((e as Error).message)}finally{setLoading(false)}},[]);
useEffect(()=>{const timer=window.setTimeout(()=>void reload(),0);return()=>window.clearTimeout(timer)},[reload]);
useEffect(()=>{const listener=()=>{if(!edit&&!habitEdit&&!auth)void reload()};window.addEventListener('focus',listener);return()=>window.removeEventListener('focus',listener)},[reload,edit,habitEdit,auth]);
const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
const ensure=()=>{if(!profile){setAuth(true);return false}return true};
const newRecord=(kind:Kind)=>{if(ensure())setEdit({id:'',kind,date:today(),data:{},revision:1})};
const visibleHabits=(profile?habits:presets()).filter(h=>h.active&&!settings.hidden.includes(h.category));
const monthly=records.filter(r=>r.date.startsWith(month));const sleeps=monthly.filter(r=>r.kind==='sleep'),studies=monthly.filter(r=>r.kind==='study'),meals=monthly.filter(r=>r.kind==='meal'),checks=monthly.filter(r=>r.kind==='check'&&r.data.complete);
const sleepValues=sleeps.map(r=>sleepHours(r.data)).filter((x):x is number=>x!==null);const avgSleep=sleepValues.length?(sleepValues.reduce((a,b)=>a+b,0)/sleepValues.length).toFixed(1):'—';
const canteen=meals.filter(r=>typeof r.data.canteen==='boolean');const mealTimes=meals.flatMap(r=>[r.data.lunchMinutes,r.data.dinnerMinutes]).filter((x):x is number=>typeof x==='number');const cleans=habits.filter(h=>h.category==='清洁'&&h.active);const cleanTarget=cleans.reduce((a,h)=>a+(h.target||countDue(h,month)),0);const cleanCount=checks.filter(r=>r.data.category==='清洁').length;
const isChecked=(h:Habit,d:string)=>records.some(r=>r.kind==='check'&&r.date===d&&r.data.complete&&(r.data.habitId===h.id||r.data.name===h.name));
const toggle=(h:Habit,d:string)=>{if(!ensure())return;void run(async()=>{await api('check','POST',{habitId:h.id,date:d,complete:!isChecked(h,d)});await reload()})};
const importFile=(f:File)=>{if(!ensure())return;void run(async()=>{const {importExcel}=await import('@/lib/excel');setImported(await importExcel(f))})};
const exportData=(all=false)=>{if(!ensure())return;void run(async()=>{const {exportExcel}=await import('@/lib/excel');await exportExcel(records,habits,all?'':month);toast.success('Excel 已导出')})};
useEffect(()=>{type MC={registerTool:(t:unknown,o:{signal:AbortSignal})=>void};const mc=(document as Document&{modelContext?:MC}).modelContext;if(!mc?.registerTool)return;const ac=new AbortController();try{mc.registerTool({name:'open_life_record_form',description:'打开生活记录表单，不保存记录',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['sleep','study','meal']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{kind:string})=>{if(!['sleep','study','meal'].includes(input.kind))throw new Error('Unknown record kind');if(!profile)return {error:'Sign in first'};setEdit({id:'',kind:input.kind as Kind,date:today(),data:{},revision:1});return {opened:input.kind}}},{signal:ac.signal})}catch{}return()=>ac.abort()},[profile]);
function recordList(items:LifeRecord[]){return items.length?<div className="record-list">{items.map(r=>{const Icon=icons[r.kind];return <article className="record-row" key={r.id}><div className="record-icon"><Icon/></div><button className="record-main" onClick={()=>setDetail(r)}><span className="record-date">{r.date}</span><strong>{recordTitle(r)}</strong><p>{recordDetail(r)}</p></button><div className="row-actions"><Button size="icon" variant="ghost" aria-label="编辑记录" onClick={()=>setEdit(r)}><Pencil/></Button><Button size="icon" variant="ghost" aria-label="删除记录" onClick={()=>setRemove(r)}><Trash2/></Button></div></article>})}</div>:<div className="empty-state"><BookOpen/><h3>这一页，等你慢慢写</h3><p>本月暂无记录，不必补满每一天。</p><Button variant="outline" onClick={()=>newRecord(tab as Kind)}><Plus/>添加一条记录</Button></div>}
return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><Toaster position="top-center" richColors/><Sidebar><SidebarHeader><div className="brand"><Leaf/><div>薄荷溪居<small>MINT & STREAM</small></div></div></SidebarHeader><SidebarContent><span className="nav-caption">我的生活手记</span><SidebarMenu>{navs.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={page===n.id} onClick={()=>setPage(n.id)}><n.Icon/><span>{n.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-bouquet"><img src="/bouquet.png" alt="薄荷兰花与奶黄色玫瑰水彩花束"/></div></SidebarContent><SidebarFooter><button className="account-caption" onClick={()=>profile?setPage('settings'):setAuth(true)}><Leaf size={18}/><span>{profile?.name||'我的私人空间'}<small>{profile?'仅自己可见':'登录后保存生活记录'}</small></span></button></SidebarFooter></Sidebar>
<main className="workspace"><header className="topbar"><div><SidebarTrigger/><span>{navs.find(n=>n.id===page)?.name}</span></div><div><span className="muted"><Lock size={13}/> 默认私密</span><Button variant="ghost" size="icon" aria-label="刷新数据" onClick={()=>void reload()}><RefreshCw size={17}/></Button>{profile?<Button variant="ghost" onClick={()=>void run(async()=>{const revoked=await logout();await reload();toast.success(revoked?'已退出登录':'本机已退出，远端会话稍后可在设备管理中撤销')})}><LogOut/>退出登录</Button>:<Button variant="outline" onClick={()=>setAuth(true)}>{setup?'创建空间':'登录'}</Button>}</div></header>
<div className="page-content">{loadError&&<div className="notice error">{loadError}<Button variant="ghost" onClick={()=>void reload()}>重新连接</Button></div>}{!loading&&!profile&&!loadError&&<div className="notice"><Lock size={16}/><span>{setup?'先创建你的私人空间，记录就能持续保存。':'登录后查看自己的生活记录。'}</span><Button variant="link" onClick={()=>setAuth(true)}>{setup?'创建空间':'登录'}<ChevronRight/></Button></div>}
{page==='home'&&<><section className="hero"><img src="/landscape.png" alt="植物屋顶小屋旁的小溪与花草水彩画"/><div className="hero-copy"><p className="eyebrow">MY QUIET EVERYDAY</p><h1>把日子，慢慢过好。</h1><p>留一点时间，照顾生活里的自己。</p><Button onClick={()=>newRecord('sleep')}><Plus/> 记录今天</Button></div></section><section className="section-title"><h2>这个月的生活</h2><Input type="month" aria-label="统计月份" className="month-input" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></section><div className="metrics">{[{Icon:Moon,title:'平均睡眠',value:avgSleep,unit:'小时',note:sleeps.length?`目标 ${settings.sleepGoal} 小时 · 已记录 ${sleeps.length} 天`:'本月暂无记录',kind:'sleep'},{Icon:BookOpen,title:'学习投入',value:studies.length?(studies.reduce((a,r)=>a+Number(r.data.actual||0),0)/60).toFixed(1):'—',unit:'小时',note:`${studies.filter(r=>r.data.complete).length} 项已完成 · 日目标 ${settings.studyGoal} 分钟`,kind:'study'},{Icon:Sprout,title:'运动打卡',value:checks.length?checks.filter(r=>r.data.category==='运动').length:'—',unit:'次',note:'每次投入，都算数',kind:'运动'},{Icon:Droplets,title:'食堂用餐率',value:canteen.length?Math.round(canteen.filter(r=>r.data.canteen).length/canteen.length*100):'—',unit:'%',note:'按已填写的天数统计',kind:'meal'}].filter(m=>!settings.hidden.includes(m.kind)).map(m=><div className="metric" key={m.title}><m.Icon/><span>{m.title}</span><strong>{m.value}<small> {m.unit}</small></strong><p>{m.note}</p></div>)}</div><div className="submetrics"><span>不熬夜率 <b>{sleeps.length?Math.round(sleeps.filter(r=>onTime(r.data,settings.bedtime)).length/sleeps.length*100)+'%':'—'}</b></span><span>平均单餐 <b>{mealTimes.length?Math.round(mealTimes.reduce((a,b)=>a+b,0)/mealTimes.length)+' 分钟':'—'}</b></span><span>清洁完成率 <b>{cleanTarget&&cleanCount?Math.round(cleanCount/cleanTarget*100)+'%':'—'}</b></span><span>本月记录 <b>{monthly.length} 条</b></span></div>
<section className="overview-columns"><div><div className="section-title"><h2>今日小事</h2><span className="muted">{today().slice(5).replace('-',' / ')}</span></div>{visibleHabits.filter(h=>due(h,today())).sort((a,b)=>(a.category==='清洁'?-1:1)-(b.category==='清洁'?-1:1)).slice(0,5).map(h=><div className="habit-row" key={h.id}><Checkbox aria-label={'完成 '+h.name} checked={isChecked(h,today())} disabled={busy} onCheckedChange={()=>toggle(h,today())}/><div><strong className={isChecked(h,today())?'done':''}>{h.name}</strong><p>{h.category} · {frequencyText(h)}</p></div>{isChecked(h,today())?<Check size={15}/>:<span className="muted">待完成</span>}</div>)}{!visibleHabits.some(h=>due(h,today()))&&<p className="empty-inline">今天没有固定安排，按自己的节奏来。</p>}<Button variant="link" className="more-link" onClick={()=>setPage('habits')}>查看全部习惯 <ArrowUpRight/></Button></div><div className="quick-panel"><p className="eyebrow">A LITTLE EVERY DAY</p><h2>给今天留一笔</h2><p>睡得好吗？今天学到了什么？</p><div className="quick-grid">{(['sleep','study','meal'] as Kind[]).filter(k=>!settings.hidden.includes(k)).map(k=>{const Icon=icons[k];return <Button variant="outline" key={k} onClick={()=>newRecord(k)}><Icon/>{labels[k]}<Plus size={14}/></Button>})}<Button variant="outline" onClick={()=>setPage('habits')}><Sprout/>打卡<ArrowUpRight size={14}/></Button></div><div className="focus-note"><span>本月重点</span><p>{settings.focusByMonth?.[month]||'还没有写下本月重点'}</p><Button variant="link" onClick={()=>{if(ensure())setPage('settings')}}>调整目标 <Pencil size={13}/></Button></div></div></section><section className="rhythm"><div className="section-title"><h2>生活的足迹</h2><span className="muted">{month.replace('-',' 年 ')} 月</span></div><div className="day-grid">{Array.from({length:daysInMonth(month)},(_,i)=>{const d=month+'-'+String(i+1).padStart(2,'0');const n=monthly.filter(r=>r.date===d).length;return <button key={d} className={'day-cell '+(n?'recorded':'')+(d===today()?' today':'')} title={`${d} · ${n} 条记录`} onClick={()=>{setDay(d);setPage('records');setTab('all')}}><span>{i+1}</span><small>{n?`${n} 笔`:'·'}</small></button>})}</div></section></>}
{page==='records'&&<><div className="page-heading"><div><p className="eyebrow">DAILY JOURNAL</p><h1>日常记录</h1><p>把细小的变化，留在这里。</p></div><Button onClick={()=>newRecord(tab==='all'?'sleep':tab as Kind)}><Plus/>添加记录</Button></div><div className="toolbar"><Tabs value={tab} onValueChange={v=>{setTab(v);setDay('')}}><TabsList variant="line"><TabsTrigger value="all">全部</TabsTrigger>{(['sleep','study','meal'] as const).filter(k=>!settings.hidden.includes(k)).map(k=><TabsTrigger key={k} value={k}>{labels[k]}</TabsTrigger>)}</TabsList></Tabs><div><Input type="month" aria-label="记录月份" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setDay('')}}}/><Button variant="outline" disabled={busy} onClick={()=>exportData()}><Download/>导出</Button></div></div>{day&&<div className="filter-note">仅查看 {day}<Button variant="ghost" size="sm" onClick={()=>setDay('')}><X/>清除日期筛选</Button></div>}{recordList(monthly.filter(r=>(tab==='all'||r.kind===tab)&&(!day||r.date===day)))}</>}
{page==='habits'&&<><div className="page-heading"><div><p className="eyebrow">SMALL RITUALS</p><h1>习惯打卡</h1><p>重复的小事，也能让生活安稳。</p></div><Button onClick={()=>{if(ensure())setHabitEdit({id:'',name:'',category:habitTab as Habit['category'],frequency:'daily',days:[1],monthDay:1,minutes:0,target:0,active:true,revision:1})}}><Plus/>新建习惯</Button></div><div className="toolbar"><Tabs value={habitTab} onValueChange={setHabitTab}><TabsList variant="line">{['运动','清洁','每日 SOP'].map(k=><TabsTrigger key={k} value={k}>{k}</TabsTrigger>)}</TabsList></Tabs><Input type="date" aria-label="打卡日期" value={day||today()} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></div><p className="help-text">勾选后保存，可补记过去的日期。停用项目仍保留历史记录。</p>{(profile?habits:presets()).filter(h=>h.category===habitTab).map(h=>{const date=day||today();const count=records.filter(r=>r.kind==='check'&&r.date.startsWith(date.slice(0,7))&&r.data.complete&&(r.data.habitId===h.id||r.data.name===h.name)).length;const target=h.target||countDue(h,date.slice(0,7));return <div className={'habit-row expanded '+(!h.active?'inactive':'')} key={h.id}><Checkbox aria-label={'完成 '+h.name} checked={isChecked(h,date)} disabled={busy||!h.active} onCheckedChange={()=>toggle(h,date)}/><div className="habit-name"><strong className={isChecked(h,date)?'done':''}>{h.name}</strong><p>{frequencyText(h)}{h.minutes?' · '+h.minutes+' 分钟':''}{!h.active?' · 已停用':due(h,date)?' · 当日安排':''}</p></div><div className="habit-progress"><span>{count} / {target} 次</span><div><i style={{width:Math.min(100,target?count/target*100:0)+'%'}}/></div></div><Button variant="ghost" size="icon" aria-label={'编辑 '+h.name} onClick={()=>{if(ensure())setHabitEdit(h)}}><Pencil/></Button></div>})}{!habits.some(h=>h.category===habitTab)&&profile&&<div className="empty-state"><Sprout/><h3>从一个简单的习惯开始</h3><p>例如晨间整理、阅读十分钟。</p></div>}</>}
{page==='settings'&&<>{profile?<SettingsPage key={month} month={month} profile={profile} onSaved={reload} onExport={exportData} onImport={importFile}/>:<div className="empty-state"><Lock/><h2>你的空间，按你的习惯设置</h2><Button onClick={()=>setAuth(true)}>登录 / 创建空间</Button></div>}</>}
<footer>薄荷溪居 <span>属于自己的生活，按自己的节奏。</span></footer></div></main>
<AuthModal open={auth} onClose={()=>setAuth(false)} setup={setup} canSetup={canSetup} setupCodeRequired={setupCodeRequired} onDone={async()=>{setAuth(false);await reload()}}/>
{edit&&<RecordModal record={edit} onClose={()=>setEdit(null)} onSave={async(r)=>{await api('record','POST',r);await reload();setEdit(null);toast.success('已保存')}}/>}
{habitEdit&&<HabitModal habit={habitEdit} onClose={()=>setHabitEdit(null)} onSave={async(h)=>{await api('habit','POST',h);await reload();setHabitEdit(null);toast.success('习惯已更新')}}/>}
<Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent><DialogHeader><DialogTitle>{detail?recordTitle(detail):''}</DialogTitle><DialogDescription>{detail?.date}</DialogDescription></DialogHeader>{detail&&<div className="detail-fields">{Object.entries(detail.data).filter(([k])=>k!=='habitId').map(([k,v])=><div key={k}><span>{fieldNames[k]||k}</span><strong>{typeof v==='boolean'?(v?'是':'否'):String(v)}</strong></div>)}</div>}</DialogContent></Dialog>
<AlertDialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>此操作无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>保留</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>void run(async()=>{await api('record/'+remove?.id,'DELETE');await reload();setRemove(null);toast.success('记录已删除')})}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
<Dialog open={!!imported} onOpenChange={v=>{if(!v)setImported(null)}}><DialogContent className="import-modal"><DialogHeader><DialogTitle>导入前，再看一眼</DialogTitle><DialogDescription>找到 {imported?.records.length||0} 条记录。分批保存，中断后可重试，已导入部分会自动跳过。已有同一天的睡眠、餐饮和同名打卡会跳过，不覆盖；学习记录按日期和内容查重。</DialogDescription></DialogHeader>{imported?.warnings.map((w,i)=><p className="help-text" key={i}>{w}</p>)}<div className="import-preview">{imported?.records.slice(0,40).map((r,i)=><div key={i}><span>{r.date} · {labels[r.kind]}</span><strong>{recordTitle(r)}</strong></div>)}</div>{(imported?.records.length||0)>40&&<p className="help-text">预览前 40 条，其余一并导入。</p>}<Button disabled={busy||!imported?.records.length} onClick={()=>void run(async()=>{const total={imported:0,skipped:0};const list=imported?.records||[];for(let i=0;i<list.length;i+=40){const r=await api<{imported:number;skipped:number}>('import','POST',{records:list.slice(i,i+40)});total.imported+=r.imported;total.skipped+=r.skipped}await reload();setImported(null);toast.success(`导入 ${total.imported} 条，跳过 ${total.skipped} 条重复记录`)})}>{busy?'正在导入…':'确认导入'}</Button></DialogContent></Dialog>
</SidebarProvider>}
const fieldNames:Record<string,string>={bed:'入睡时间',wake:'起床时间',rating:'睡眠评分',arrangement:'安排',early:'不熬夜',notes:'备注',project:'课程 / 项目',task:'任务类型',planned:'计划分钟',actual:'实际分钟',focus:'专注度',complete:'完成',breakfast:'早餐',lunch:'午餐',dinner:'晚餐',lunchMinutes:'午饭分钟',dinnerMinutes:'晚饭分钟',vegetable:'水果 / 蔬菜',canteen:'食堂至少一餐',water:'饮水',snack:'夜宵',name:'项目',category:'类别',minutes:'分钟'};
function AuthModal({open,onClose,setup,canSetup,setupCodeRequired,onDone}:{open:boolean;onClose:()=>void;setup:boolean;canSetup:boolean;setupCodeRequired:boolean;onDone:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{const data=Object.fromEntries(new FormData(e.currentTarget));await authenticate(setup?'setup':'login',data);await onDone()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent><DialogHeader><DialogTitle>{setup?'创建你的私人空间':'欢迎回来'}</DialogTitle><DialogDescription>{setup?'为自己设置邮箱和密码。账号创建后，初始化入口将永久关闭。':'登录后继续记录生活。'}</DialogDescription></DialogHeader><form onSubmit={submit} className="form-stack">{setup&&<Field label="昵称"><Input name="name" required maxLength={40} autoComplete="nickname"/></Field>}{setup&&setupCodeRequired&&<Field label="空间创建码"><Input name="setupCode" type="password" required autoComplete="off"/></Field>}<Field label="邮箱"><Input name="email" type="email" required autoComplete="email"/></Field><Field label="密码（至少 12 位）"><Input name="password" type="password" required minLength={12} maxLength={200} autoComplete={setup?'new-password':'current-password'}/></Field>{error&&<p role="alert" className="form-error">{error}</p>}{setup&&!canSetup&&<p className="form-error">尚未配置个人空间创建条件，请先完成部署设置。</p>}<Button disabled={busy||(setup&&!canSetup)}>{busy?'请稍候…':setup?'创建空间':'登录'}</Button><p className="help-text">这是个人单账号空间。请妥善保存密码。</p></form></DialogContent></Dialog>}
function RecordModal({record,onClose,onSave}:{record:LifeRecord;onClose:()=>void;onSave:(r:LifeRecord)=>Promise<void>}){const [r,setR]=useState(record),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string|number|boolean)=>setR({...r,data:{...r.data,[k]:v}});const input=(k:string,type='text',required=false)=> <Input type={type} required={required} value={String(r.data[k]??'')} min={type==='number'?0:undefined} maxLength={type==='text'?300:undefined} onChange={e=>{if(type==='number'&&e.target.value===''){const data={...r.data};delete data[k];setR({...r,data})}else set(k,type==='number'?Number(e.target.value):e.target.value)}}/>;const pick=(k:string,opts:string[])=> <Pick value={String(r.data[k]||'未填写')} onChange={v=>{if(v==='未填写'){const data={...r.data};delete data[k];setR({...r,data})}else set(k,['rating','focus'].includes(k)?Number(v):v)}} options={['未填写',...opts]} label={fieldNames[k]}/>;const yesno=(k:string)=><Pick value={typeof r.data[k]==='boolean'?(r.data[k]?'yes':'no'):'unset'} onChange={v=>{if(v==='unset'){const d={...r.data};delete d[k];setR({...r,data:d})}else set(k,v==='yes')}} options={[["unset","未填写"],["yes","是"],["no","否"]]} label={fieldNames[k]}/>;
return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="record-modal"><DialogHeader><DialogTitle>{record.id?'编辑':'记录'}{labels[r.kind]}</DialogTitle><DialogDescription>保存到自己的空间，可随时修改。</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(r)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="form-grid"><Field label="日期"><Input type="date" required value={r.date} onChange={e=>setR({...r,date:e.target.value})}/></Field>{!record.id&&<Field label="记录类型"><Pick value={r.kind} onChange={v=>setR({...r,kind:v as Kind,data:{}})} options={[["sleep","睡眠"],["study","学习"],["meal","餐饮"]]}/></Field>}
{r.kind==='sleep'&&<><Field label="当天安排">{pick('arrangement',['上课','休息','考试','公休','假期'])}</Field><Field label="入睡时间">{input('bed','time',true)}</Field><Field label="起床时间">{input('wake','time',true)}</Field><Field label="睡眠评分（1–5）">{pick('rating',['1','2','3','4','5'])}</Field><div className="calculated wide">按起床日期记账；跨午夜自动计算。睡眠时长：{sleepHours(r.data)??'—'} 小时。</div></>}
{r.kind==='study'&&<><Field label="课程 / 项目">{input('project','text',true)}</Field><Field label="任务类型（可自定义）"><Input list="task-options" value={String(r.data.task||'')} onChange={e=>set('task',e.target.value)}/><datalist id="task-options">{['上课','复习','作业','实验','项目','竞赛','英语','阅读','其他'].map(t=><option key={t} value={t}/>)}</datalist></Field><Field label="计划分钟">{input('planned','number')}</Field><Field label="实际分钟">{input('actual','number',true)}</Field><Field label="专注度（1–5）">{pick('focus',['1','2','3','4','5'])}</Field><Field label="是否完成">{yesno('complete')}</Field></>}
{r.kind==='meal'&&<>{['breakfast','lunch','dinner'].map(k=><Field key={k} label={fieldNames[k]}>{pick(k,['正常','简单','没吃','外卖'])}</Field>)}<Field label="午饭时长（分钟）">{input('lunchMinutes','number')}</Field><Field label="晚饭时长（分钟）">{input('dinnerMinutes','number')}</Field><Field label="水果 / 蔬菜">{yesno('vegetable')}</Field><Field label="食堂至少一餐">{yesno('canteen')}</Field><Field label="饮水">{pick('water',['正常','较少','较多'])}</Field><Field label="夜宵">{pick('snack',['无','少量','较多'])}</Field></>}
{r.kind==='check'&&<><Field label="项目">{input('name','text',true)}</Field><Field label="完成">{yesno('complete')}</Field></>}
<Field label="备注" wide><Textarea value={String(r.data.notes||'')} maxLength={3000} onChange={e=>set('notes',e.target.value)} placeholder="想记下的细节…"/></Field></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-footer"><Button type="button" variant="ghost" onClick={onClose} disabled={busy}>取消</Button><Button disabled={busy}>{busy?'正在保存…':'保存记录'}</Button></div></form></DialogContent></Dialog>}
function HabitModal({habit,onClose,onSave}:{habit:Habit;onClose:()=>void;onSave:(h:Habit)=>Promise<void>}){const [h,setH]=useState(habit),[busy,setBusy]=useState(false),[error,setError]=useState('');return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent><DialogHeader><DialogTitle>{h.id?'调整习惯':'新建习惯'}</DialogTitle><DialogDescription>调整预设，找到适合自己的频率。</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave(h)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="form-grid"><Field label="项目名称" wide><Input value={h.name} required maxLength={120} onChange={e=>setH({...h,name:e.target.value})}/></Field><Field label="类别"><Pick value={h.category} options={['运动','清洁','每日 SOP']} onChange={v=>setH({...h,category:v as Habit['category']})}/></Field><Field label="频率"><Pick value={h.frequency} options={[["daily","每天"],["weekly","每周"],["biweekly","每两周"],["monthly","每月"]]} onChange={v=>setH({...h,frequency:v as Habit['frequency']})}/></Field>{['weekly','biweekly'].includes(h.frequency)&&<div className="wide weekday-picks">{[1,2,3,4,5,6,0].map(d=><label key={d}><Checkbox checked={h.days.includes(d)} onCheckedChange={v=>setH({...h,days:h.frequency==='biweekly'?[d]:v?[...h.days,d]:h.days.filter(x=>x!==d)})}/>{'日一二三四五六'[d]}</label>)}</div>}{h.frequency==='monthly'&&<Field label="每月几号（月底自动适配）"><Input type="number" min={1} max={31} required value={h.monthDay} onChange={e=>setH({...h,monthDay:Number(e.target.value)})}/></Field>}<Field label="每次分钟（可填 0）"><Input type="number" min={0} max={1440} value={h.minutes} onChange={e=>setH({...h,minutes:Number(e.target.value)})}/></Field><Field label="月目标次数（0 = 按频率计算）"><Input type="number" min={0} max={1000} value={h.target} onChange={e=>setH({...h,target:Number(e.target.value)})}/></Field><label className="switch-row wide"><span>启用这个习惯</span><Switch checked={h.active} onCheckedChange={v=>setH({...h,active:v})}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-footer"><Button disabled={busy}>{busy?'保存中…':'保存习惯'}</Button></div></form></DialogContent></Dialog>}
function SettingsPage({profile,onSaved,onExport,onImport,month}:{month:string;profile:Profile;onSaved:()=>Promise<void>;onExport:(all:boolean)=>void;onImport:(f:File)=>void}){const [s,setS]=useState(profile.settings),[name,setName]=useState(profile.name),[busy,setBusy]=useState(false);return <><div className="page-heading"><div><p className="eyebrow">YOUR OWN PACE</p><h1>个人设置</h1><p>留下适合自己的，其他的可以慢慢来。</p></div><SettingsIcon/></div><form className="settings-section" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('settings','POST',{name,settings:s,revision:profile.revision});await onSaved();toast.success('设置已保存')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}><h2>我的目标与偏好</h2><div className="form-grid"><Field label="昵称"><Input value={name} required onChange={e=>setName(e.target.value)}/></Field><Field label="邮箱"><Input readOnly value={profile.email}/></Field><Field label="目标睡眠（小时）"><Input type="number" min={1} max={24} step={0.5} value={s.sleepGoal} onChange={e=>setS({...s,sleepGoal:Number(e.target.value)})}/></Field><Field label="每天学习目标（分钟）"><Input type="number" min={1} max={1440} value={s.studyGoal} onChange={e=>setS({...s,studyGoal:Number(e.target.value)})}/></Field><Field label="不熬夜参考时间"><Input type="time" required value={s.bedtime} onChange={e=>setS({...s,bedtime:e.target.value})}/></Field><Field label={month+' 月重点'} wide><Textarea value={s.focusByMonth?.[month]||''} maxLength={2000} onChange={e=>setS({...s,focusByMonth:{...s.focusByMonth,[month]:e.target.value}})}/></Field></div><h3>首页显示的模块</h3><div className="module-switches">{[['sleep','睡眠'],['study','学习'],['meal','餐饮'],['运动','运动'],['清洁','清洁'],['每日 SOP','每日 SOP']].map(([k,t])=><label className="switch-row" key={k}><span>{t}</span><Switch checked={!s.hidden.includes(k)} onCheckedChange={v=>setS({...s,hidden:v?s.hidden.filter(x=>x!==k):[...s.hidden,k]})}/></label>)}</div><Button disabled={busy}>{busy?'保存中…':'保存设置'}</Button></form><section className="settings-section"><h2>记录的备份与迁入</h2><p className="help-text">支持原生活管理模板和本站导出的 .xlsx。导入前可预览，重复记录会跳过。</p><div className="button-row"><Button variant="outline" onClick={()=>onExport(false)}><Download/>导出当前月</Button><Button variant="outline" onClick={()=>onExport(true)}><FileSpreadsheet/>导出全部记录</Button><label className="file-button"><Upload size={16}/>导入 Excel<input type="file" accept=".xlsx" onChange={e=>{if(e.target.files?.[0])onImport(e.target.files[0]);e.target.value=''}}/></label></div></section></>}
