import type {LifeRecord,Data,Habit} from './life';
import {sleepHours,labels,frequencyText} from './life';
const columns:Record<string,[string,string][]>= {
sleep:[['date','日期'],['arrangement','安排'],['bed','睡觉时间'],['wake','起床时间'],['rating','睡眠评分(1-5)'],['early','不熬夜'],['notes','备注']],
study:[['date','日期'],['project','课程/项目'],['task','任务类型'],['planned','计划分钟'],['actual','实际分钟'],['complete','完成'],['focus','专注度(1-5)'],['notes','备注']],
meal:[['date','日期'],['breakfast','早餐'],['lunch','午餐'],['lunchMinutes','午饭时长'],['dinner','晚餐'],['dinnerMinutes','晚饭时长'],['vegetable','水果/蔬菜'],['canteen','食堂≥1餐'],['water','饮水'],['snack','夜宵'],['notes','备注']],
check:[['date','日期'],['name','项目'],['category','类别'],['complete','完成'],['minutes','分钟'],['notes','备注']]
};
const sheetNames={sleep:'睡眠记录',study:'学习记录',meal:'餐饮记录',check:'习惯打卡'};
export async function exportExcel(records:LifeRecord[],habits:Habit[],month:string){const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();wb.creator='薄荷溪居';for(const kind of ['sleep','study','meal','check'] as const){const ws=wb.addWorksheet(sheetNames[kind]);ws.columns=columns[kind].map(([key,header])=>({key,header,width:key==='notes'?40:22}));records.filter(r=>r.kind===kind&&(!month||r.date.startsWith(month))).forEach(r=>{const o:Record<string,unknown>={date:r.date,...r.data};for(const [k,v]of Object.entries(o))if(typeof v==='boolean')o[k]=v?'✓':'✗';ws.addRow(o)});ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:{row:1,column:ws.columnCount}};ws.getRow(1).eachCell(c=>{c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFCDE5DD'}};c.font={name:'Microsoft YaHei',size:11,bold:true,color:{argb:'FF425D52'}}});ws.eachRow(r=>{r.height=26;r.alignment={vertical:'middle',wrapText:true}})}const hs=wb.addWorksheet('预设项目');hs.columns=[{header:'项目',key:'name',width:35},{header:'类别',key:'category',width:15},{header:'频率',key:'frequency',width:45},{header:'每次分钟',key:'minutes',width:15},{header:'月目标次数',key:'target',width:15}];habits.forEach(h=>hs.addRow({...h,frequency:frequencyText(h)}));const note=wb.addWorksheet('说明');note.getCell('A1').value='此导出包含生活记录与预设项目说明；预设项目通过网站设置维护。';note.getColumn(1).width=100;const buf=await wb.xlsx.writeBuffer();download(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`薄荷溪居-${month||'全部记录'}.xlsx`)}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function plain(v:unknown):string|number|boolean|Date{if(v instanceof Date)return v;if(v&&typeof v==='object'){const o=v as {result?:unknown;text?:string;richText?:{text:string}[]};if(o.result!==undefined)return plain(o.result);if(o.text)return o.text;if(o.richText)return o.richText.map(x=>x.text).join('');return ''}return (v??'') as string|number|boolean}
function dateValue(v:unknown){v=plain(v);if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number')return new Date(Date.UTC(1899,11,30)+Math.round(v)*86400000).toISOString().slice(0,10);const s=String(v).trim().replaceAll('/','-');const m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''}
function timeValue(v:unknown){v=plain(v);if(v instanceof Date)return v.toISOString().slice(11,16);if(typeof v==='number'){const n=Math.round((v%1)*1440)%1440;return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}const m=String(v).match(/^(\d{1,2}):(\d{2})/);return m?m[1].padStart(2,'0')+':'+m[2]:''}
export async function importExcel(file:File){if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('请选择 .xlsx 格式工作簿');if(file.size>10*1024*1024)throw new Error('工作簿上限为 10 MB');const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer(),{ignoreNodes:['mergeCells','drawing','conditionalFormatting','dataValidations']});const result:LifeRecord[]=[];const warnings:string[]=[];let supported=0;
for(const kind of ['sleep','study','meal','check'] as const){const ws=wb.getWorksheet(sheetNames[kind]);if(!ws)continue;supported++;const header=Array.from({length:Math.min(5,ws.rowCount)},(_,i)=>i+1).find(i=>Array.from({length:ws.columnCount},(_,j)=>plain(ws.getRow(i).getCell(j+1).value)).includes('日期'));if(!header)continue;const map:Record<string,number>={};ws.getRow(header).eachCell((c,i)=>{map[String(plain(c.value))]=i});for(let n=header+1;n<=Math.min(ws.rowCount,10000);n++){const row=ws.getRow(n);const d:Data={};let date='';for(const [key,title]of columns[kind]){const raw=map[title]?plain(row.getCell(map[title]).value):'';if(key==='date'){date=dateValue(raw);continue}if(raw==='')continue;if(['bed','wake'].includes(key))d[key]=timeValue(raw);else if(['complete','early','vegetable','canteen'].includes(key))d[key]=raw===true||['✓','是','已完成'].includes(String(raw));else if(['actual','planned','rating','focus','minutes','lunchMinutes','dinnerMinutes'].includes(key)){if(Number.isFinite(Number(raw)))d[key]=Number(raw);else if(['lunchMinutes','dinnerMinutes'].includes(key))warnings.push(`${sheetNames[kind]}第 ${n} 行的餐时为“${raw}”，无法换算分钟，已留空`)}else d[key]=String(raw)}const meaningful=kind==='sleep'?d.bed||d.wake:kind==='study'?d.project:kind==='meal'?Object.keys(d).some(k=>k!=='notes'):d.name;if(!meaningful)continue;if(!date||kind==='sleep'&&(!d.bed||!d.wake)||kind==='study'&&d.actual===undefined){warnings.push(`${sheetNames[kind]}第 ${n} 行缺少必填内容，已跳过`);continue}result.push({id:'',kind,date,data:d,revision:1})}}
for(const [name,category]of [['健身记录','运动'],['清洁记录','清洁'],['每日SOP','每日 SOP']]){const ws=wb.getWorksheet(name);if(!ws)continue;supported++;const dateRow=2;for(let r=6;r<=Math.min(ws.rowCount,name==='健身记录'?16:1000);r++){const item=String(plain(ws.getRow(r).getCell(name==='清洁记录'?3:1).value));if(!item)continue;for(let c=name==='清洁记录'?6:3;c<=Math.min(ws.columnCount,name==='清洁记录'?36:33);c++){if(plain(ws.getRow(r).getCell(c).value)!=='✓')continue;const date=dateValue(ws.getRow(dateRow).getCell(c).value);if(!date){warnings.push(`${name}的日期公式无缓存，无法读取该次打卡；请用 Excel 打开并保存后再导入`);continue}result.push({id:'',kind:'check',date,data:{name:item,category,complete:true},revision:1})}}}
if(!supported)throw new Error('未找到支持的生活记录工作表。请使用“大学生活管理模板”或本站导出的工作簿。');if(result.length>300)throw new Error('每次最多 300 条，请按月份拆分导入');return {records:result,warnings:[...new Set(warnings)]}}
