import {env} from 'cloudflare:workers';
import {defaultSettings,presets,type LifeRecord,type Habit} from './life';
export const runtime=env as unknown as {DB:D1Database;MINT_LOCAL_SETUP?:string;MINT_OWNER_EMAIL?:string;MINT_SETUP_TOKEN?:string};
export function db(){if(!runtime.DB)throw new Error('数据库尚未配置');return runtime.DB}
export function json(value:unknown,status=200,headers:Record<string,string>={}){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export function fail(status:number,msg:string):never{throw new ApiError(status,msg)}
export async function body(req:Request){const raw=await req.text();if(raw.length>2_000_000)fail(413,'内容过大');try{return JSON.parse(raw)}catch{fail(400,'无效的请求内容')}}
export const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(n=>n.toString(16).padStart(2,'0')).join('');
export const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)).buffer);
export async function hash(s:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
export async function passwordHash(p:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
export function equal(a:string,b:string){let result=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)result|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return result===0}
export type User={id:string;email:string;name:string;settings:string;revision:number};
export async function user(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)mint_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;return await db().prepare('SELECT u.id,u.email,u.name,u.settings,u.revision FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?').bind(await hash(token),Date.now()).first<User>()}
export async function mustUser(req:Request){const u=await user(req);if(!u)fail(401,'请先登录');return u}
export function csrf(req:Request){if(req.method==='GET')return;const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)fail(403,'请求来源不匹配，请刷新后重试')}
export async function limit(key:string,max=12){const now=Date.now();const r=await db().prepare('INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN attempts.until<? THEN 1 ELSE attempts.count+1 END,until=CASE WHEN attempts.until<? THEN excluded.until ELSE attempts.until END RETURNING count').bind(key,now+900000,now,now).first<{count:number}>();if(r&&r.count>max)fail(429,'尝试次数过多，请 15 分钟后重试')}
export async function session(id:string,req:Request){const token=random();await db().prepare('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)').bind(await hash(token),id,Date.now()+7*86400000).run();return `mint_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export function cleanUser(u:User){return {...u,settings:{...defaultSettings,...JSON.parse(u.settings)}}}
export async function seedHabits(){await db().batch(presets().map(h=>db().prepare('INSERT OR IGNORE INTO habits(id,payload) VALUES(?,?)').bind(h.id,JSON.stringify(h))))}
export function unpack(r:Record<string,unknown>):LifeRecord{return {...r,data:JSON.parse(String(r.payload))} as unknown as LifeRecord}
export function validateRecord(r:LifeRecord){if(!r||!['sleep','study','meal','check'].includes(r.kind)||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||new Date(r.date+'T12:00:00Z').toISOString().slice(0,10)!==r.date)fail(400,'记录类别或日期无效');if(!r.data||typeof r.data!=='object'||Array.isArray(r.data)||JSON.stringify(r.data).length>15000)fail(400,'记录内容无效');for(const [k,v] of Object.entries(r.data)){if(!['string','number','boolean'].includes(typeof v))fail(400,'字段内容无效');if(typeof v==='number'&&(!Number.isFinite(v)||v<0||v>100000))fail(400,'数值不在允许范围');if(['bed','wake'].includes(k)&&v&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(String(v)))fail(400,'时间格式无效')}if(r.kind==='sleep'&&(!r.data.bed||!r.data.wake||r.data.bed===r.data.wake))fail(400,'请填写不同的入睡和起床时间');if(r.kind==='study'&&(!String(r.data.project||'').trim()||r.data.actual===undefined))fail(400,'请填写课程/项目和实际分钟');for(const k of ['rating','focus'])if(r.data[k]!==undefined&&r.data[k]!==''&&(!Number.isFinite(+r.data[k])||+r.data[k]<1||+r.data[k]>5))fail(400,'评分范围为 1–5');}
export function validateHabit(h:Habit){if(!h.name?.trim()||h.name.length>120||!['运动','清洁','每日 SOP'].includes(h.category)||!['daily','weekly','biweekly','monthly'].includes(h.frequency)||!Array.isArray(h.days)||h.days.some(d=>!Number.isInteger(d)||d<0||d>6)||h.monthDay<1||h.monthDay>31||h.target<0||h.target>1000||h.minutes<0||h.minutes>1440)fail(400,'习惯项目或频率无效');if(['weekly','biweekly'].includes(h.frequency)&&!h.days.length)fail(400,'请至少选择一个星期')}
export async function guard(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof ApiError)return json({error:e.message},e.status);console.error('Request failed',e instanceof Error?e.message:'unknown');return json({error:'暂时无法完成操作，请稍后重试。输入内容已保留。'},503)}}
